```{r}
#| label: load packages

library(tidyverse)
library(readr)
```


```{r}
#| label: data cleaning

#2020
file_path <- "data/2020.txt"
Election2020 <- read_tsv(file_path)

Election2020 <- Election2020 |>
  rename(Total_Votes = `Total Votes`, Choice_Party = `Choice Party`)

Election2020_Summary <- Election2020 |>
  filter(`Contest Name` == "US PRESIDENT") |>
  filter(Choice_Party %in% c("DEM", "REP")) |>
  group_by(County, Choice_Party) |>
  summarize(Total_Votes = sum(Total_Votes, na.rm = TRUE), .groups = 'drop') |>
  arrange(County, Choice_Party) 

Election2020_Summary$Year <- 2020
  

#2016
file_path <- "data/2016.txt"
Election2016 <- read_tsv(file_path)

Election2016 <- Election2016 |>
  rename(Total_Votes = `Total Votes`, Choice_Party = `Choice Party`)

Election2016_Summary <- Election2016 |>
  filter(`Contest Name` == "US PRESIDENT") |>
  filter(Choice_Party %in% c("DEM", "REP")) |>
  group_by(County, Choice_Party) |>
  summarize(Total_Votes = sum(Total_Votes, na.rm = TRUE), .groups = 'drop') |>
  arrange(County, Choice_Party)

Election2016_Summary$Year <- 2016

#2012
file_path <- "data/2012.txt"
Election2012 <- read_delim(file_path, delim = ",")

Election2012 <- Election2012 |>
  rename(`Total_Votes` = `total votes`, County = county, `Choice_Party` = party) 

Election2012_Summary <- Election2012 |>
  filter(contest == "PRESIDENT AND VICE PRESIDENT OF THE UNITED STATES") |>
  filter(Choice_Party %in% c("DEM", "REP")) |>
  group_by(County, Choice_Party) |>
  summarize(Total_Votes = sum(Total_Votes, na.rm = TRUE), .groups = 'drop') |>
  arrange(County, Choice_Party)

Election2012_Summary$Year <- 2012

#2008
file_path <- "data/2008.txt"
Election2008 <- read_delim(file_path, delim = ",")

Election2008 <- Election2008 |>
  rename(`Total_Votes` = `total votes`, County = county, `Choice_Party` = party) 

Election2008_Summary <- Election2008 |>
  filter(contest == "PRESIDENT AND VICE PRESIDENT OF THE UNITED STATES") |>
  filter(Choice_Party %in% c("DEM", "REP")) |>
  group_by(County, Choice_Party) |>
  summarize(Total_Votes = sum(Total_Votes, na.rm = TRUE), .groups = 'drop') |>
  arrange(County, Choice_Party)

Election2008_Summary$Year <- 2008

#2004
file_path <- "data/2004.txt"
Election2004 <- read_delim(file_path, delim = ",")

Election2004 <- Election2004 |>
  rename(`Total_Votes` = ballot_count, County = county, `Choice_Party` = party_cd) 

head(Election2004)
Election2004_Summary <- Election2004 |>
  filter(contest_name == "PRESIDENT") |>
  filter(Choice_Party %in% c("DEM", "REP")) |>
  group_by(County, Choice_Party) |>
  summarize(Total_Votes = sum(Total_Votes, na.rm = TRUE), .groups = 'drop') |>
  arrange(County, Choice_Party)

Election2004_Summary$Year <- 2004

#2000
file_path <- "data/2000.txt"
Election2000 <- read_tsv(file_path, col_names = FALSE)

Election2000 <- Election2000 |>
  rename(`Total_Votes` = X8, County = X1, `Choice_Party` = X7, `contest` = X5) 

Election2000_Summary <- Election2000 |>
  filter(contest == "PRESIDENT-VICE PRESIDENT") |>
  filter(Choice_Party %in% c("DEM", "REP")) |>
  group_by(County, Choice_Party) |>
  summarize(Total_Votes = sum(Total_Votes, na.rm = TRUE), .groups = 'drop') |>
  arrange(County, Choice_Party)

Election2000_Summary$Year <- 2000
```

```{r}
election_data <- rbind(Election2000_Summary, Election2004_Summary, Election2008_Summary, 
                       Election2012_Summary, Election2016_Summary, Election2020_Summary)
```

```{r}
#| label: adding in geographical data and creating final dataframe

geography_nc <- read_csv("data/NCCounties2.csv")
separate_geo <- geography_nc |>
  separate(col = `Spreadsheet List of All counties in North Carolina.csv_exported`,
           into = c("County", "Lat", "Long"), sep = ",", convert = TRUE)
#set values manually for Alamance because they are NAs in the original dataset
separate_geo <- separate_geo |>
  mutate(
    Lat = if_else(County == "Alamance", "36.0117", Lat),  
    Long = if_else(County == "Alamance", "-79.4254", Long)  
  ) |>
  #drop the one empty row
  filter(County != "")
separate_geo <- separate_geo |>
   slice(-1) 
separate_geo$County <- toupper(separate_geo$County)
#election_data_geo <- select(election_data_geo, -Lat, -Long)

#reshaping total votes into dem and rep votes
election_data_wide <- election_data |>
  pivot_wider(
    names_from = Choice_Party,
    values_from = Total_Votes,
    names_prefix = "Votes_"
 ) |>
  replace_na(list(Votes_DEM = 0, Votes_REP = 0))

#adding in geographical data
election_data_wide_geo <- left_join(election_data_wide, separate_geo, by = "County")

#adding in shape data for polygons
polygon_nc <- read_csv("NCDOT_County_Boundaries.csv")

```

```{r}
#| label: write csv file to data folder for app
write_csv(election_data_wide_geo, "../../project-2-team_spring/NorthCarolinaApp/data for app/election_data_wide_geo.csv")
write_csv(election_data_wide_geo, "../../project-2-team_spring/NorthCarolinaApp/data for app/election-data-geo.csv")
```

